### ISSUE TITLE
add snippets/functions

### ISSUE THREAD

**Issue by rohan472000** [rohan472000/SnippetHub#3]
@Diegomangasco , Hey, would you be interested in contributing to my repo by adding some useful snippets/functions? I think you could really add value to the project.

**Comment by Diegomangasco** [comment]
> @Diegomangasco , Hey, would you be interested in contributing to my repo by adding some useful snippets/functions? I think you could really add value to the project.

Hi @rohan472000 I really would like to contribute to this project!
